networks:
  pantos-ethereum:
    driver: overlay
    name: pantos-ethereum-${STACK_IDENTIFIER}-${INSTANCE-1}
    attachable: true

services:
  eth:
    restart: always
    image: pantosio/ethereum-node:${DOCKER_TAG-local}
    build:
      context: .
      dockerfile: Dockerfile
      target: blockchain-node
      x-bake:
        tags:
          - ${DOCKER_REGISTRY-pantosio}/ethereum-node:${DOCKER_TAG-local}
          - ${DOCKER_REGISTRY-pantosio}/ethereum-node:${EXTRA_TAG-local}
    networks:
      pantos-ethereum:
    environment:
      CHAIN_ID: 31337
    volumes:
      # Workaround so that we can also access the data locally
      # Without needing an additional container
    - type: volume
      source: eth-data
      target: /data
    - type: bind
      source: "${DATA_PATH-./data}/eth"
      target: /data2
    healthcheck:
      test: ["CMD-SHELL", "cast block-number"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
  bnb:
    restart: always
    image: pantosio/ethereum-node:${DOCKER_TAG-local}
    build:
      context: .
      dockerfile: Dockerfile
      target: blockchain-node
      x-bake:
        tags:
          - ${DOCKER_REGISTRY-pantosio}/ethereum-node:${DOCKER_TAG-local}
          - ${DOCKER_REGISTRY-pantosio}/ethereum-node:${EXTRA_TAG-local}
    networks:
      pantos-ethereum:
    volumes:
      # Workaround so that we can also access the data locally
      # Without needing an additional container
    - type: volume
      source: bnb-data
      target: /data
    - type: bind
      source: "${DATA_PATH-./data}/bnb"
      target: /data2
    environment:
      CHAIN_ID: 31338
    healthcheck:
      test: ["CMD-SHELL", "cast block-number"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  eth-data:
    name: eth-data-${STACK_IDENTIFIER}-${INSTANCE-1}
  bnb-data:
    name: bnb-data-${STACK_IDENTIFIER}-${INSTANCE-1}
