name: Publish dev release
on:
  push:
    branches:
      - main

jobs:
  publish-docker:
    uses: ./.github/workflows/publish-docker.yaml
    if: github.repository == 'pantos-io/ethereum-contracts'
    secrets: 'inherit'
    with:
      tag: development
      architecture: amd64
      environment: main

  test:
    needs: publish-docker
    uses: pantos-io/e2e-testing/.github/workflows/ci.yaml@main
