name: Update PR summary

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
    static-analysis:
        name: Static analysis
        runs-on: ubuntu-latest
        permissions:
          actions: read
          contents: read
          pull-requests: write
        steps:
          - uses: step-security/harden-runner@v2
            with:
              egress-policy: audit    
          - name: Create/update checklist as PR comment
            uses: actions/github-script@v7
            if: github.event_name == 'pull_request'
            env:
              REPORT: ${{ steps.slither.outputs.stdout }}
            with:
              script: |
                // const script = require('.github/scripts/comment')
                // const header = '# Slither report'
                // const body = process.env.REPORT
                // await script({ github, context, header, body })
                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: process.env.REPORT
                })
    

            







